import { MenuItem } from '@/types/menu';

export const defaultMenuItems: MenuItem[] = [
  {
    id: 'demo-1',
    name: 'Tajine Poulet Citron',
    name_ar: 'طاجين الدجاج بالليمون',
    description: 'Poulet mijoté avec citron confit, olives vertes et épices marocaines.',
    description_ar: 'دجاج مطهو ببطء مع الليمون المخلل والزيتون الأخضر والتوابل المغربية.',
    price: 145,
    category: 'plats',
    tags: ['chef-choice', 'traditionnel', 'épicé'],
    imageUrl: '/logo.png',
    available: true,
    aiDescription: 'Un classique revisité, cuisiné lentement pour des saveurs profondes.',
    popularityScore: 92,
    ingredients: ['Poulet', 'Citron confit', 'Olives vertes', 'Oignons', 'Épices marocaines'],
    allergens: [],
    preparationTime: 45,
    calories: 420,
    spicyLevel: 1,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isChefSpecial: true,
    createdAt: new Date('2024-01-05T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z')
  },
  {
    id: 'demo-2',
    name: 'Salade The Kitch',
    name_ar: 'سلطة ذا كيتش',
    description: 'Mélange de salades fraîches, noix croquantes et vinaigrette maison.',
    description_ar: 'مزيج من السلطات الطازجة والمكسرات المقرمشة وصوص الخل المنزلي.',
    price: 85,
    category: 'entrees',
    tags: ['végétarien', 'healthy', 'fresh'],
    imageUrl: '/logo.png',
    available: true,
    aiDescription: 'Fraîcheur et textures contrastées avec une touche d’agrumes.',
    popularityScore: 80,
    ingredients: ['Salade mixte', 'Noix', 'Agrumes', 'Vinaigrette maison'],
    allergens: ['Noix'],
    preparationTime: 15,
    calories: 280,
    spicyLevel: 0,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isChefSpecial: false,
    createdAt: new Date('2024-01-10T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z')
  },
  {
    id: 'demo-3',
    name: 'Pastilla au Poulet',
    name_ar: 'بسطيلة بالدجاج',
    description: 'Feuilleté sucré-salé, amandes torréfiées et cannelle.',
    description_ar: 'رقائق رقيقة بطعم حلو مالح، لوز محمص وقرفة.',
    price: 155,
    category: 'plats',
    tags: ['traditionnel', 'signature'],
    imageUrl: '/logo.png',
    available: true,
    popularityScore: 88,
    ingredients: ['Poulet', 'Amandes', 'Cannelle', 'Feuilles de brick'],
    allergens: ['Noix', 'Gluten'],
    preparationTime: 50,
    calories: 540,
    spicyLevel: 0,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isChefSpecial: true,
    createdAt: new Date('2024-01-12T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z')
  },
  {
    id: 'demo-4',
    name: 'Mille-feuille Pistache',
    name_ar: 'ميلفوي بالفستق',
    description: 'Pâte feuilletée croustillante, crème pistache légère.',
    description_ar: 'عجينة مورقة مقرمشة مع كريمة فستق خفيفة.',
    price: 75,
    category: 'desserts',
    tags: ['nouveau', 'gourmand'],
    imageUrl: '/logo.png',
    available: true,
    popularityScore: 76,
    ingredients: ['Pâte feuilletée', 'Crème pistache', 'Sucre'],
    allergens: ['Lait', 'Gluten', 'Noix'],
    preparationTime: 20,
    calories: 360,
    spicyLevel: 0,
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isChefSpecial: false,
    createdAt: new Date('2024-01-15T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z')
  },
  {
    id: 'demo-5',
    name: 'Thé à la Menthe',
    name_ar: 'شاي بالنعناع',
    description: 'Thé vert infusé à la menthe fraîche et sucre léger.',
    description_ar: 'شاي أخضر بالنعناع الطازج وسكر خفيف.',
    price: 35,
    category: 'boissons',
    tags: ['classique'],
    imageUrl: '/logo.png',
    available: true,
    popularityScore: 70,
    ingredients: ['Thé vert', 'Menthe', 'Sucre'],
    allergens: [],
    preparationTime: 10,
    calories: 90,
    spicyLevel: 0,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isChefSpecial: false,
    createdAt: new Date('2024-01-20T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z')
  },
  {
    id: 'demo-6',
    name: 'Assiette Rabat Signature',
    name_ar: 'طبق الرباط المميز',
    description: 'Sélection de spécialités locales avec légumes grillés.',
    description_ar: 'تشكيلة من الأطباق المحلية مع خضار مشوية.',
    price: 175,
    category: 'specials',
    tags: ['signature', 'local'],
    imageUrl: '/logo.png',
    available: true,
    popularityScore: 84,
    ingredients: ['Agneau', 'Légumes grillés', 'Herbes fraîches'],
    allergens: [],
    preparationTime: 35,
    calories: 480,
    spicyLevel: 1,
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isChefSpecial: true,
    createdAt: new Date('2024-01-22T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z')
  }
];

export const defaultMenuByCategory = defaultMenuItems.reduce<Record<string, MenuItem[]>>(
  (acc, item) => {
    acc[item.category] = acc[item.category] || [];
    acc[item.category].push(item);
    return acc;
  },
  {}
);
